### ISSUE TITLE
Add Merge Sort in cpp

### ISSUE THREAD

**Issue by Saikatssd** [ssgshubham/repo-0#8]
Please assign this to me.
Please add Hacktoberfest 2022 labels.

**Comment by 7smn2219** [comment]
I can do it in 10 min.
Please assign this to me.
Please add Hacktoberfest 2022 labels.

**Comment by Jitesh02** [comment]
I have proper knowledge of sorting so, Please assign this to me.
Please add Hacktoberfest 2022 labels.
